apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange
    environment: Development
  name: exchange
  namespace: api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: exchange
  sessionAffinity: None
  type: ClusterIP
