apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Api
  labels:
    app: exchange
    environment: Development
    tier: Service
  name: exchange
  namespace: api
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
      name: exchange
    spec:
      containers:
      - name: exchange
        image: docker.io/swisschains/api-exchange:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: SeqUrl
          value: "http://seq.common"
        - name: RemoteSettingsUrl
          valueFrom:
            secretKeyRef:
              name: exchange
              key: RemoteSettingsUrl